pipeline {
    agent { label= ubuntu}

    environment {
        SONARQUBE_ENV = 'sonarqube-server'
        IMAGE_NAME = 'java-app'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                    sh '''
                    mvn sonar:sonar \
                    -Dsonar.projectKey=java-app \
                    -Dsonar.projectName=java-app
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:latest .'
            }
        }
    }

    post {
        success {
            echo 'Build, SonarQube analysis, and Docker image creation completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}

