pipeline {
    agent { label "Raju" }

    environment {
        SONARQUBE_ENV = 'sonarqube-server'
        IMAGE_NAME = 'java-app'
    }

    stages {

        stage('Build') {
            steps {
                dir('java-app') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

  stage('SonarQube Analysis') {
      steps {
        dir('java-app') {
            withSonarQubeEnv('sonarqube-server') {
                withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                    sh '''
                      mvn sonar:sonar \
                      -Dsonar.projectKey=java-app \
                      -Dsonar.projectName=java-app \
                      -Dsonar.login=$SONAR_TOKEN
                    '''
                 }
              }
          }
       } 
    }


       

        stage('Docker Build') {
            steps {
                dir('java-app') {
                    sh "docker build -t ${IMAGE_NAME}:latest ."
                }
            }
        }
    }

    post {
        success {
            echo 'Build, SonarQube analysis, Quality Gate, and Docker image completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
